### ISSUE TITLE
Anything I can do to help make this mod better?

### ISSUE THREAD

**Issue by AirTechWick** [boardengineer/Brotatogether#2]
I am new to Unity, but willing to learn any Unity concepts or Networking to help this mod become better

**Comment by boardengineer** [comment]
This is actually in godot

**Comment by AirTechWick** [comment]
My bad I confused this game with another one that uses Unity. But, I am comfortable with Godot!

**Comment by AirTechWick** [comment]
Is their anything that I can work on for this mod?

**Comment by boardengineer** [comment]
There's just general debugging, i don't have anything very specific to point to but people are always finding some crash or another t hat would be nice to track down.

I think there's a bug with versus hp display not updating.

I don't think the end game on either format works quite right

**Comment by AirTechWick** [comment]
How feasible would it be if I added a revive feature?

**Comment by boardengineer** [comment]
what do you have in mind?

**Comment by carbonNine** [comment]
hey @AirTechWick ... Can you possibly implement local co-op for this game? Atleast 4 person co-op with controller support.
'Bounty of One' has this feature and would love for this game to have something similar.
